project:
  type: website
  output-dir: docs
  resources:
    - lectures/**
  render:
    - "*.qmd"

website:
  title: "DATASCI 385"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: false
  repo-url: https://github.com/danilofreire/datasci385
  repo-actions: [issue, source]
  repo-branch: gh-pages
  navbar:
    pinned: true
    tools:
      - icon: github
        href: https://github.com/danilofreire/datasci385
    left:
      - href: syllabus.qmd
        text: Syllabus
        icon: journal-text
      - href: lectures.qmd
        text: Lectures
        icon: mortarboard
      - href: assignments.qmd
        text: Assignments
        icon: pencil-square
      - href: guides.qmd
        text: Guides
        icon: compass
      - href: LICENSE.html
        text: " "
  page-footer: 
    left: "The content of this site is licensed under the [MIT License](LICENSE.qmd)." 
    right: 
      - icon: github
        href: https://github.com/danilofreire/datasci385

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss, custom-dark.scss]
    css: styles.css
    mainfont: "Source Sans 3"
    monofont: "Inconsolata"
    highlight-style: github
    toc: true

